### ISSUE TITLE
Map response to model without RxSwift

### ISSUE THREAD

**Issue by futantan** [ivanbruel/Moya-ObjectMapper#12]
Hi, it works well when I use it with RxSwift, but when I try to do it without Rx here the problem comes.

```swift
if let repos = try response.mapArray(Repository)
```
but the compiler give me an error: 

`Argument passed to call that takes no arguments`

the generic function:

```swift
public func mapArray<T: Mappable>() throws -> [T]
```

how to fix it? Or I did it in a wrong way?

**Comment by ivanbruel** [comment]
You are right, the documentation is wrong at the moment.

try to call it this way:
```swift
if let repos: [Repository] = try response.mapArray()
```

I'll be updating the API to match the documentation and your example.

```swift
if let repos = try response.mapArray(Repository)
```

This will be the API from the next version forward.

**Comment by futantan** [comment]
It works! Thank you!

**Comment by tianxiewuhua** [comment]
my issue is map object ....... is this right ? "if let login: LoginResponse = try response.mapObject()"
PS: why not update the document ?

**Comment by ivanbruel** [comment]
The new `1.3` version is out and the API has been standardized. it is now always `mapObject(Class)` or `mapArray(Class)` for both reactive and non-reactive APIs.
