### ISSUE TITLE
Update for Moya 7.0.0

### ISSUE THREAD

**Issue by wattson12** [ivanbruel/Moya-ObjectMapper#15]
Hi, 

Recently Moya updated to [version 7.0.0](https://github.com/Moya/Moya/releases/tag/7.0.0) so it would be cool to update this library to support that version. 

I tried to do this myself, but haven't been able to satisfy the pod install for the sample project using an updated podspec. I was seeing this error:

```
[!] Unable to satisfy the following requirements:

- `Moya/ReactiveCocoa (~> 7.0)` required by `Moya-ObjectMapper/ReactiveCocoa (1.3)`
```

Happy to submit a PR if anyone has any ideas about why this isn't working

**Comment by matteogazzato** [comment]
Hi @wattson12 , 
by now i have done a fork and modify ".podspec" file, changing the version dependency for Moya

```
s.subspec "Core" do |ss|
    ss.source_files  = "Source/*.swift"
    ss.dependency "Moya", "~> 7.0"
    ss.dependency "ObjectMapper", "~> 1.3"
    ss.framework  = "Foundation"
end
```
If you want here there is my fork:
[https://github.com/matteogazzato/Moya-ObjectMapper.git](https://github.com/matteogazzato/Moya-ObjectMapper.git)

Anyway i hope @ivanbruel will update the podspec :)

**Comment by ivanbruel** [comment]
Merged from your fork @matteogazzato, should be working for everyone!
I'll be closing this issue for the meantime, in case there's any incompatibility open a new issue!

**Comment by wattson12** [comment]
Thanks for the quick response everyone, really appreciated
