### ISSUE TITLE
support for swift-3.0?

### ISSUE THREAD

**Issue by georgetso** [ivanbruel/Moya-ObjectMapper#20]

**Comment by andrewwells** [comment]
+1

**Comment by ivanbruel** [comment]
I will add support for Swift 3.0 when Moya releases a Swift 3.0 version, which should be soon https://github.com/Moya/Moya/pull/608

**Comment by Legoless** [comment]
I needed this earlier, so I have a version that works with Swift 3.0 for RxSwift. I don't have time to double check everything, but if you create another branch @ivanbruel I'll submit a PR and you guys can help. https://github.com/legoless/Moya-ObjectMapper

**Comment by davidlondono** [comment]
add support at least on another branch, Moya have done it

**Comment by kwosu87** [comment]
+1 @Legoless I've been looking for Moya Mapper supporting Swift 3.0. Thanks for your working and hope that will be merged to this repository :)

**Comment by atomic-avocado** [comment]
I wasn't able to use Legoless branch. 
Am I doing anything wrong?
pod 'Moya-ObjectMapper'', :git => 'https://github.com/legoless/Moya-ObjectMapper',  :branch => 'master'

**Comment by Legoless** [comment]
I use it the same way, even without specifying master branch. It has likely to do with other pods, there might be version conflicts, or you are using ReactiveCocoa?

**Comment by atomic-avocado** [comment]
No. I use RxSwift / RxCocoa... I'll try again this weekend... it might be just something I missed cuz I was lazy xD. Thanks for the quick response tho. 👍

**Comment by Legoless** [comment]
No problem, if you still get problems, give us more information, entire pod file and the errors you get.

**Comment by ivanbruel** [comment]
@Legoless please open a PR into the master branch, thanks!

**Comment by atomic-avocado** [comment]
Ok, so I installed the pod and got 264 errors all from Alamofire. The test app is just a blank app btw.

![screen shot 2016-09-24 at 5 45 12 pm](https://cloud.githubusercontent.com/assets/12943776/18811202/9e667c9e-827f-11e6-9db4-7ac92cab0564.png)

`Pre-downloading: `Moya-ObjectMapper` from `https://github.com/legoless/Moya-ObjectMapper`
Downloading dependencies
Installing Alamofire (3.5.0)
Using Bolts (1.8.4)
Using FBSDKCoreKit (4.15.1)
Using FBSDKLoginKit (4.15.1)
Using FSCalendar (2.3.3)
Using Material (2.0.0)
Installing Moya (7.0.2)
Installing Moya-ObjectMapper (1.4)
Using NSStringMask (1.2)
Installing ObjectMapper (2.0.0)
Installing Result (2.1.3)
Using RxCocoa (3.0.0-beta.1)
Using RxSwift (3.0.0-beta.1)
Using TPKeyboardAvoiding (1.3)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 8 dependencies from the Podfile and 14 total pods installed.`

These are the pods I'm using.
	pod 'RxSwift',    '~> 3.0.0-beta.1'
    pod 'RxCocoa',    '~> 3.0.0-beta.1'
	pod 'Material', :git => 'https://github.com/CosmicMind/Material', :branch => 'development'
	pod 'FSCalendar', '~> 2.3'
	pod 'NSStringMask', '~> 1.2'
	pod 'FBSDKLoginKit', '~> 4.15'
	pod 'TPKeyboardAvoiding', '~> 1.3'
	pod 'Moya-ObjectMapper', :git => 'https://github.com/legoless/Moya-ObjectMapper'

**Comment by ivanbruel** [comment]
Working on it, will get back to you guys, merged #22 in the meantime.

**Comment by ivanbruel** [comment]
I released a Swift 3.0 version, seems to be working properly on the Demo project. I'll keep this open until all dependencies officially release their Swift 3.0 versions on CocoaPods.
