### ISSUE TITLE
Update for rxswift and moya

### ISSUE THREAD

**Issue by pluckq** [ivanbruel/Moya-ObjectMapper#21]
Could you please provide update for new dependencies? 

[!] Unable to satisfy the following requirements:
- `RxSwift (= 3.0.0-beta.1)` required by `Podfile.lock`
- `RxSwift (~> 3.0.0-beta.1)` required by `RxCocoa (3.0.0-beta.1)`
- `RxSwift (= 3.0.0-beta.1)` required by `Moya/RxSwift (7.0.0)`
- `RxSwift (= 2.0.0-beta.4)` required by `Moya-ObjectMapper/RxSwift (1.0.2)`

**Comment by ivanbruel** [comment]
I've published the `1.4` version with support for Swift 2.3. A later release will support Swift 3.0 but I'm waiting on Moya's Swift 3.0 release version.

**Comment by juliengdt** [comment]
Yes, Moya Swift 3.0 exist already but no tag has been pushed for this version.

Maybe just by asking a ```swift-3.0``` beta tag linjed with the swift 3.0 branch could help

Swift 3.0 merging is really a pain in the *ss 😭

**Comment by ivanbruel** [comment]
Yeah, I was looking into how I could apply Moya for Swift 3.0 through the podpsec, seems it's a problem for the time being.

**Comment by wattson12** [comment]
Looks like there should be a version of Moya to reference through the podspec now: https://github.com/Moya/Moya/releases/tag/8.0.0-beta.1 (I think marked as beta because RxSwift is marked as beta)

**Comment by juliengdt** [comment]
@wattson12 wouhouu !! 🎉

**Comment by ivanbruel** [comment]
Seems to no longer be an issue :)
