### ISSUE TITLE
Please add Carthage support.

### ISSUE THREAD

**Issue by lexrus** [ivanbruel/Moya-ObjectMapper#3]
Every dependence of this lib has Carthage support.

**Comment by mpdomas** [comment]
+1

**Comment by ivanbruel** [comment]
I have zero experience with Carthage, especially with how to replicate subspecs, but I'll accept pull requests for it.

**Comment by ivanbruel** [comment]
With the addition of a Demo project, how hard would it be to migrate to a Carthage project?

**Comment by embassem** [comment]
+1

**Comment by ivanbruel** [comment]
Still accepting PRs on this 👍

**Comment by wuaschtikus** [comment]
+ 1
