### ISSUE TITLE
Why it required >9.0 deployment target

### ISSUE THREAD

**Issue by XuNeal** [ivanbruel/Moya-ObjectMapper#30]
when I add  
` pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/ivanbruel/Moya-ObjectMapper' ` to my Podfile and install it return

`Specs satisfying the `Moya-ObjectMapper/RxSwift (from `https://github.com/ivanbruel/Moya-ObjectMapper`)` dependency were found, but they required a higher minimum deployment target.`

Is there any way I can set the deployment target 8.0 ?

**Comment by ivanbruel** [comment]
I'm unsure why the podspec actually has over the top minimum deployment targets, let me look into it and get back to you.

**Comment by ivanbruel** [comment]
Submitted a new version to cocoapods hopefully fixing this issue.
Let me know if that works out for you so I can close this issue.
