### ISSUE TITLE
Is it necessary to required by a settled RxSwift & ObjectMapper version

### ISSUE THREAD

**Issue by whlsxl** [ivanbruel/Moya-ObjectMapper#31]
My podfile is 

>   pod 'RxSwift',    '~> 3.0'
>   pod 'ObjectMapper', '-> 2.2.1'
>   pod 'Moya', '8.0.0-beta.5'
>   pod 'Moya-ObjectMapper'
>   pod 'Moya-ObjectMapper/RxSwift'

I got this error when `pod install`

[!] Unable to satisfy the following requirements:

- `ObjectMapper (~> 2.2.1)` required by `Podfile`
- `ObjectMapper (~> 2.2.1)` required by `Podfile`
- `ObjectMapper (= 2.2.2)` required by `Podfile.lock`
- `ObjectMapper (= 2.2.1)` required by `Moya-ObjectMapper/Core (2.2)`
- `Moya (= 8.0.0-beta.5)` required by `Podfile`
- `Moya (= 8.0.0-beta.5)` required by `Podfile`
- `Moya (= 8.0.0-beta.5)` required by `Podfile.lock`
- `Moya (= 8.0.0-beta.3)` required by `Moya-ObjectMapper/Core (2.0.1)`
- `Moya/RxSwift` required by `Podfile`
- `Moya/RxSwift` required by `Podfile`
- `Moya/RxSwift (= 8.0.0-beta.5)` required by `Podfile.lock`
- `Moya/RxSwift (~> 5.3.0)` required by `Moya-ObjectMapper/RxSwift (1.1.0)`
- `RxSwift (~> 3.0)` required by `Podfile`
- `RxSwift (~> 3.0)` required by `Podfile`
- `RxSwift (= 3.0.1)` required by `Podfile.lock`
- `RxSwift (~> 3.0)` required by `Moya/RxSwift (8.0.0-beta.5)`
- `RxSwift (~> 3.0)` required by `RxCocoa (3.0.1)`
- `RxSwift (~> 3.0)` required by `RxDataSources (1.0.0)`
- `RxSwift (= 2.0.0-beta.4)` required by `Moya-ObjectMapper/RxSwift (1.0.2)`

**Comment by ivanbruel** [comment]
This should be fixed by now, closing it.
