### ISSUE TITLE
rxswift example

### ISSUE THREAD

**Issue by Niphery** [ivanbruel/Moya-ObjectMapper#32]
Is there somewhere a rxswift example?

When I follow the following rxSwift Doc:
```
RxMoyaProvider<APIService>(endpointClosure: endpointClosure, plugins: [plugins])
			.request(service)
			.debug("Moya")
			.mapObject(Repository)
```
I get the error message:
`Value of type 'Observable<Response>' has no member 'mapObject'`

**Comment by Niphery** [comment]
I realized I needed to import the file `Observable+ObjectMapper.swift` manually.
I'm not sure if it is intended. If so you should mention it somewhere.

**Comment by anhar** [comment]
@Niphery I am having the exact same problem as you had. 
Could please elaborate a bit further on how you imported the `Observable+ObjectMapper.swift` manually? Do you mean importing it to your `<APPNAME>.xcodeproj`?

Are you using cocoapods?

Here's the `Podfile.lock`file I am using at the moment:
```
PODS:
  - Alamofire (4.2.0)
  - Moya (8.0.0):
    - Moya/Core (= 8.0.0)
  - Moya-ObjectMapper (2.3):
    - Moya-ObjectMapper/Core (= 2.3)
  - Moya-ObjectMapper/Core (2.3):
    - Moya (>= 8.0.0)
    - ObjectMapper (= 2.2.2)
  - Moya/Core (8.0.0):
    - Alamofire (~> 4.2.0)
    - Result (~> 3.1.0)
  - Moya/RxSwift (8.0.0):
    - Moya/Core
    - RxSwift (~> 3.1.0)
  - ObjectMapper (2.2.2)
  - Result (3.1.0)
  - RxBlocking (3.0.1):
    - RxSwift (~> 3.0)
  - RxCocoa (3.0.1):
    - RxSwift (~> 3.0)
  - RxSwift (3.1.0)
  - RxTest (3.0.1):
    - RxSwift (~> 3.0)
```

**Comment by Niphery** [comment]
@anhar if you download the library, there is a file in the source called `Observable+ObjectMapper.swift`, this file is not in imported if you just use cocoa pods.
So just get the library and import the file manually in your project. (drag & drop)

**Comment by ivanbruel** [comment]
Hey there guys, are you installing with `pod Moya-ObjectMapper/RxSwift` instead of `pod Moya-ObjectMapper` ?

**Comment by Niphery** [comment]
That would explain our issue.
I didn't notice it an rx version of object mapper was available separately from OM itself. :(
Thanks for pointing it out 👍
