### ISSUE TITLE
Moya-ObjectMapper/ReactiveCocoa don't exist

### ISSUE THREAD

**Issue by EvilNOP** [ivanbruel/Moya-ObjectMapper#34]
When using cocopods instal Moya-ObjectMapper/ReactiveCocoa got an error:

None of your spec sources contain a spec satisfying the dependency: `Moya-ObjectMapper/ReactiveCocoa (from `https://github.com/ivanbruel/Moya-ObjectMapper`)`.

Then I pod search it Moya-ObjectMapper, found out only Moya-ObjectMapper/RxSwift available.

So, could please release the Moya-ObjectMapper/ReactiveCocoa? Cuz I am using ReactiveCocoa, not RxSwift.

**Comment by ivanbruel** [comment]
This is mostly to the fact that ReactiveCocoa (or ReactiveSwift) has not been updated on cocoapods and cannot be published as a dependency.
