### ISSUE TITLE
Please update the dependent version to 3.1.

### ISSUE THREAD

**Issue by Abel94** [ivanbruel/Moya-ObjectMapper#35]
Rxswift 3.1 has been released, the current dependence of this library and other libraries will be in conflict, please update the dependency information, thank you!

**Comment by Ank49** [comment]
Would be great to update the dependence version of RxSwift asap, can't install it because it requires 3.0.1 when RxCocoa and RxRealm both require 3.1.0 …
Any fix while not updated ?

**Comment by ivanbruel** [comment]
Version 2.3 brings this update, closing it.
