### ISSUE TITLE
Question about rewite

### ISSUE THREAD

**Issue by gperdomor** [ivanbruel/Moya-ObjectMapper#50]
i made a new mapper for a personal project, i build from zero and conforms the swift api guidelines... My idea is not replace your project or pod, but if you like, we can merge both repos :D...

The repo is https://github.com/gperdomor/MoyaObjectMapper

let me know what you think :D

**Comment by ivanbruel** [comment]
Thank you for your issue, feel free to create a pull request if you want to contribute.
