### ISSUE TITLE
RxSwift example not working

### ISSUE THREAD

**Issue by patrikqvarnstrom** [ivanbruel/Moya-ObjectMapper#53]
Example gives several errors. 

.mapArray(Repository) gives "Expected member name or constructor call after type name"

    GitHubProvider.request(.userRepositories(username))
      .mapArray(Repository)
      .subscribe { event -> Void in
        switch event {
        case .next(let repos):
          self.repos = repos
        case .error(let error):
         print(error)
        default:
         break
       }
      }.addDisposableTo(disposeBag)

Do you have a working example for implementing this together with RxSwift? Would be amazing if you could make one. :)

**Comment by starr0stealer** [comment]
What are some of the `errors` you are getting, the one noted above used to be a warning pre `Swift 3.1`, which is basically saying to add `.self` so it should be `.mapArray(Repository.self)`.

Any further errors may be with the `Moya Provider`, you need to make sure you're using `RxMoyaProvider`. Give the [Moya Docs](https://github.com/Moya/Moya/blob/master/docs/ReactiveSwift.md) a read for how to set it up.

**Comment by patrikqvarnstrom** [comment]
Was using a wrong import, my bad closing this :). But the .self thing was an actual error tho so maybe update the documentation when you have time. Thanks for the help!
