### ISSUE TITLE
Getting issue as below for MapObject 

### ISSUE THREAD

**Issue by iOSUser110** [ivanbruel/Moya-ObjectMapper#56]
function signature specialization <preserving fragile attribute, Arg[1] = [Closure Propagated : reabstraction thunk helper from @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> () to @callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> (@out ()), Argument Types : [@callee_owned (@unowned Swift.UnsafeBufferPointer<Swift.UInt8>) -> ()]> of generic specialization <preserving fragile attribute, ()> of Swift.StaticString.withUTF8Buffer <A> ((Swift.UnsafeBufferPointer<Swift.UInt8>) -> A) -> A

**Comment by ivanbruel** [comment]
Without much information, this seems to be an issue regarding Moya or ObjectMapper and not actually Moya-ObjectMapper.
I suggest you file a an issue in https://github.com/Hearst-DD/ObjectMapper and/or https://github.com/Moya/Moya
