### ISSUE TITLE
Initializer for conditional binding must have Optional type, not '[T]'

### ISSUE THREAD

**Issue by arietis** [ivanbruel/Moya-ObjectMapper#59]
After ObjectMapper 2.2.7 release the library doesn't compile anymore.

Response+ObjectMapper.swift
Error:(27, 56) initializer for conditional binding must have Optional type, not '[T]'

**Comment by mendesbarreto** [comment]
Hello guys I have the same problem on my project

**Comment by joeytat** [comment]
Same here.

**Comment by MacroYau** [comment]
I've just updated my project's libraries and found the same issue. My workaround is to revert ObjectMapper version to 2.2.6 in `Moya-ObjectMapper.podspec`. You may apply this fix by pointing `pod` entry to my fork's `podspec`:

```ruby
pod 'Moya-ObjectMapper/RxSwift', :podspec => 'https://raw.githubusercontent.com/MacroYau/Moya-ObjectMapper/master/Moya-ObjectMapper.podspec'
```
