### ISSUE TITLE
Rxswift + Moya + Moya-ObjectMapper Error handling

### ISSUE THREAD

**Issue by Alexandeer** [ivanbruel/Moya-ObjectMapper#60]
I have two mappable classes: "Hospital" and "ErrorAPI"

How can i "mapObject()" my custom error? I mean, if the server responds with an error, then I want to process it as a mappable object.

```
JSON error
{
"status" : "401",
"errorsMessage" : "abc"
...
}
```
My code:
```
let provider = RxMoyaProvider<APIClient>()

requestHospitalButton.rx_tap
    .withLatestFrom(hospitalCode)
    .flatMapLatest { [unowned self] code in
        self.provider.request(.Hospital(code: code))
     }
     .mapObject(Hospital)
     .subscribe { [unowned self] event in
         switch event {
         case .Next(let hospital):
             // success (Hospital)
         case .Error(let error):
             // error (Now it string, but i need obj ErrorAPI as Hospital in case .Next)
         default: break
         }
     }
     .addDisposableTo(rx_disposeBag)
```

I'm new to these libraries. Thanks for any help.

**Comment by ivanbruel** [comment]
I'd suggest you take a look at https://github.com/ivanbruel/RxResult for how to handle this particular issue. You can mix and match both libraries and add your custom error mapper to the `static func failure(from error: Error) -> Self` and subscribe the result afterwards

**Comment by Alexandeer** [comment]
Thanks
