### ISSUE TITLE
Early RxSwift 4 support?

### ISSUE THREAD

**Issue by alexisbronchart** [ivanbruel/Moya-ObjectMapper#69]
Is there already an early version supporting RxSwift 4 somewhere?

**Comment by levibostian** [comment]
It's no longer early, but RxSwift 4 and Moya 10 can be obtained from my PR: https://github.com/ivanbruel/Moya-ObjectMapper/pull/75. 

If you want to use it before it gets merged:

```
pod 'Moya-ObjectMapper/RxSwift', :git => 'https://github.com/levibostian/Moya-ObjectMapper.git', :branch => 'swift4'
```

**Comment by shimaazmy** [comment]
It fails to download when i try to `pod install`
