### ISSUE TITLE
Moya-ObjectMapper

### ISSUE THREAD

**Issue by NareshChoudhari** [ivanbruel/Moya-ObjectMapper#73]
# Nobody Helping about this Moya-ObjectMapper error, Could please help about this issue.
Its required any mac specifications using like Xcode 9, swift 3, macOsSieraa version -10.12.6

- Getting the pods error as shown below 
![screen shot 2017-10-06 at 4 47 51 pm](https://user-images.githubusercontent.com/29284442/31275992-451aa686-aab7-11e7-9317-38c48752fc6d.png)
![screen shot 2017-10-06 at 4 48 26 pm](https://user-images.githubusercontent.com/29284442/31275999-488d3bd0-aab7-11e7-8056-248a5f513b28.png)
![screen shot 2017-10-06 at 4 59 44 pm](https://user-images.githubusercontent.com/29284442/31276112-cf8e371a-aab7-11e7-819a-a1d5e343dd21.png)

- Can't able to install the Moya-ObjectMapper in new project.

- I used these pods in my project.
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'Moya', '8.0.3'
    pod 'Moya/RxSwift'
    pod 'Swinject', '2.0.0'
    pod 'SwinjectStoryboard', '1.0.0'
    pod 'R.swift'
    pod 'SwiftyBeaver'
    pod 'Moya-ObjectMapper'
    pod 'Moya-ObjectMapper/RxSwift'
    pod 'BEMCheckBox'
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'Cosmos', '~> 10.0'
    pod 'Mixpanel-swift'
    pod 'FacebookCore'

I also tried adding the Observable+Mapper.swift separately to the project , but still no luck.
Any help will be appreciated. Thank you
I

**Comment by arfaa-shariff** [comment]
* Looks like the version in your pod file is different from that of in the podfile.lock .
* Observable+ObjectMapper.swift was replaced with Single+ObjectMapper in release 2.4. 
* Instead use the following dependency pod 'Moya-ObjectMapper/RxSwift',    '~> 2.3.2’

**Comment by NareshChoudhari** [comment]
Hey arfaa, its works pod 'Moya-ObjectMapper/RxSwift', '~> 2.3.2’ ThankYou so much

**Comment by NareshChoudhari** [comment]
Hey arfaa, pod 'Moya-ObjectMapper/RxSwift', '~> 2.3.2’ its works great ThankYou so much
